name: Java Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Setup Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3 - Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4 - Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Step 5 - Build & Run Tests
      - name: Build with Maven
        run: mvn clean test -B
