name: Java Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3 - Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4 - Setup ChromeDriver
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # Step 5 - Kill leftover Chrome processes (prevents session conflicts)
      - name: Kill stale Chrome processes
        run: pkill -f chrome || true

      # Step 6 - Build & Run Maven Tests
      - name: Run Maven Tests
        run: mvn clean test -B -Dsurefire.printSummary=true

      # Step 7 - Upload Surefire test reports
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      # Step 8 - Upload screenshots on failure
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots/
